import { useState } from 'react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { X, Loader2, Shield, AlertCircle, Check } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { api, type PricingSource, type PricingSourceCreate } from '@/lib/api'

interface Props {
  source?: PricingSource | null
  onClose: () => void
  onSuccess: () => void
}

const PROVIDER_TYPES = [
  { value: 'openrouter', label: 'OpenRouter' },
  { value: 'litellm', label: 'LiteLLM' },
  { value: 'openai', label: 'OpenAI' },
  { value: 'anthropic', label: 'Anthropic' },
  { value: 'google', label: 'Google' },
  { value: 'custom', label: 'Custom' },
] as const

const REFRESH_INTERVALS = [
  { value: 'immediate', label: 'Immediate' },
  { value: 'hourly', label: 'Hourly' },
  { value: 'daily', label: 'Daily' },
  { value: 'weekly', label: 'Weekly' },
  { value: 'monthly', label: 'Monthly' },
  { value: 'manual', label: 'Manual' },
] as const

export default function PricingSourceModal({ source, onClose, onSuccess }: Props) {
  const qc = useQueryClient()
  const [name, setName] = useState(source?.name || '')
  const [description, setDescription] = useState(source?.description || '')
  const [providerType, setProviderType] = useState<PricingSource['provider_type']>(
    source?.provider_type || 'openrouter'
  )
  const [apiUrl, setApiUrl] = useState(source?.api_url || '')
  const [apiKey, setApiKey] = useState('')
  const [is_active, setIsActive] = useState(source?.is_active ?? true)
  const [default_refresh_interval, setDefaultRefreshInterval] = useState<PricingSource['default_refresh_interval']>(
    source?.default_refresh_interval || 'monthly'
  )
  const [showApiSuccess, setShowApiSuccess] = useState(false)

  const mutation = useMutation({
    mutationFn: (body: PricingSourceCreate) => {
      if (source) {
        return api.pricingSources.update(source.id, body)
      }
      return api.pricingSources.create(body)
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['pricing-sources'] })
      onSuccess()
    },
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()

    const body: PricingSourceCreate = {
      name,
      description: description || null,
      provider_type: providerType,
      api_url: apiUrl || null,
      api_key_encrypted: apiKey || null,
      api_key_iv: null, // Will be generated by backend if needed
      is_active,
      default_refresh_interval,
    }

    mutation.mutate(body)
  }

  const isEditing = !!source

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30">
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-lg mx-4 p-6">
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-2">
            <Shield size={16} className="text-[#4f7dff]" />
            <h2 className="text-sm font-display font-600 text-[#0f1117]">
              {isEditing ? 'Edit Pricing Source' : 'Add Pricing Source'}
            </h2>
          </div>
          <button onClick={onClose} className="text-[#9099b0] hover:text-[#0f1117]">
            <X size={16} />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Name */}
          <div>
            <label className="block text-xs text-[#6b7380] mb-1.5 font-mono uppercase tracking-wider">
              Name <span className="text-red-500">*</span>
            </label>
            <Input
              placeholder="e.g., OpenRouter API"
              value={name}
              onChange={e => setName(e.target.value)}
              required
            />
          </div>

          {/* Description */}
          <div>
            <label className="block text-xs text-[#6b7380] mb-1.5 font-mono uppercase tracking-wider">
              Description
            </label>
            <Input
              placeholder="Optional description"
              value={description}
              onChange={e => setDescription(e.target.value)}
            />
          </div>

          {/* Provider Type */}
          <div>
            <label className="block text-xs text-[#6b7380] mb-1.5 font-mono uppercase tracking-wider">
              Provider Type <span className="text-red-500">*</span>
            </label>
            <div className="grid grid-cols-3 gap-2">
              {PROVIDER_TYPES.map(pt => (
                <button
                  key={pt.value}
                  type="button"
                  onClick={() => setProviderType(pt.value as any)}
                  className={`px-2 py-2 rounded-lg text-xs capitalize text-center transition-all ${
                    providerType === pt.value
                      ? 'bg-[#4f7dff]/10 text-[#0f1117] border border-[#4f7dff]/25 font-medium'
                      : 'bg-white text-[#6b7380] border border-black/10 hover:bg-black/3'
                  }`}
                >
                  {pt.label}
                </button>
              ))}
            </div>
          </div>

          {/* API URL (for custom/openrouter) */}
          {providerType === 'openrouter' || providerType === 'custom' ? (
            <div>
              <label className="block text-xs text-[#6b7380] mb-1.5 font-mono uppercase tracking-wider">
                API Base URL
              </label>
              <Input
                placeholder="https://api.openrouter.ai/v1"
                value={apiUrl}
                onChange={e => setApiUrl(e.target.value)}
              />
            </div>
          ) : null}

          {/* API Key */}
          <div>
            <label className="block text-xs text-[#6b7380] mb-1.5 font-mono uppercase tracking-wider">
              API Key <span className="text-[#9099b0] normal-case">(encrypted in DB)</span>
            </label>
            <Input
              type="password"
              placeholder="sk-..."
              value={apiKey}
              onChange={e => setApiKey(e.target.value)}
            />
            {showApiSuccess && (
              <div className="flex items-center gap-1.5 text-xs text-green-600 mt-1">
                <Check size={12} /> API key saved securely
              </div>
            )}
          </div>

          {/* Refresh Interval */}
          <div>
            <label className="block text-xs text-[#6b7380] mb-1.5 font-mono uppercase tracking-wider">
              Default Refresh Interval
            </label>
            <div className="grid grid-cols-3 gap-2">
              {REFRESH_INTERVALS.map(ri => (
                <button
                  key={ri.value}
                  type="button"
                  onClick={() => setDefaultRefreshInterval(ri.value as any)}
                  className={`px-2 py-2 rounded-lg text-xs capitalize text-center transition-all ${
                    default_refresh_interval === ri.value
                      ? 'bg-[#4f7dff]/10 text-[#0f1117] border border-[#4f7dff]/25 font-medium'
                      : 'bg-white text-[#6b7380] border border-black/10 hover:bg-black/3'
                  }`}
                >
                  {ri.label}
                </button>
              ))}
            </div>
          </div>

          {/* Active Toggle */}
          <div className="flex items-center justify-between">
            <div>
              <label className="text-xs text-[#6b7380] font-medium">Active</label>
              <p className="text-[10px] text-[#9099b0]">Enable to use this source for sync</p>
            </div>
            <button
              type="button"
              onClick={() => setIsActive(!is_active)}
              className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                is_active ? 'bg-[#4f7dff]' : 'bg-[#d1d5de]'
              }`}
            >
              <span
                className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                  is_active ? 'translate-x-6' : 'translate-x-1'
                }`}
              />
            </button>
          </div>

          {/* Error message */}
          {mutation.isError && (
            <div className="flex items-center gap-2 text-xs text-red-600 bg-red-50 p-2 rounded-lg">
              <AlertCircle size={14} />
              {(mutation.error as Error).message}
            </div>
          )}

          <div className="flex justify-end gap-2 pt-2 border-t border-black/8">
            <Button type="button" variant="ghost" size="sm" onClick={onClose}>
              Cancel
            </Button>
            <Button type="submit" size="sm" disabled={mutation.isPending}>
              {mutation.isPending ? (
                <Loader2 size={13} className="animate-spin" />
              ) : isEditing ? (
                'Save Changes'
              ) : (
                'Create Source'
              )}
            </Button>
          </div>
        </form>

        {/* Info for LiteLLM (no key needed) */}
        {providerType === 'litellm' && (
          <div className="mt-4 rounded-lg bg-blue-50 border border-blue-100 p-3">
            <div className="flex items-start gap-2 text-xs text-blue-700">
              <div className="mt-0.5">
                <Shield size={12} />
              </div>
              <div>
                <p className="font-medium mb-1">LiteLLM uses public pricing data</p>
                <p className="text-[11px]">
                  No API key required - pricing is fetched from the LiteLLM GitHub repository.
                </p>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
